spring.application.name=Lost-Found

# MongoDB Configuration
spring.mongodb.uri=mongodb+srv://root:root@lost-found.8t0ys57.mongodb.net/lostfound_db?retryWrites=true&w=majority&appName=Lost-Found

# Multipart File Limits (Allow images up to 10MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Cloudinary Credentials
cloudinary.cloud-name=bwqx1tmq
cloudinary.api-key=792187873736116
cloudinary.api-secret=DeNZ5PmYjHOY3tbzTDSi_FHvPJw