spring.application.name=LAB-FINAL-PREP
server.port=8080

spring.mongodb.uri=mongodb+srv://class:advancejava@spring-mongo.szx1t5k.mongodb.net/LAB-FINAL-PREP?appName=spring-mongo

spring.datasource.url=jdbc:mysql://localhost:3306/lab_final_prep?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=true

spring.thymeleaf.cache=false
